import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import ReduxStoreProvider from "@/redux-toolkit/provider";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Toaster from "@/components/Toaster/Toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxStoreProvider>
          <Toaster/>
          <Header />
          {children}
          <Footer />
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
